"""empty message

Revision ID: 0a37a4ac9fe9
Revises: 7875ad37a9a9
Create Date: 2018-04-06 21:38:36.987315

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0a37a4ac9fe9'
down_revision = '7875ad37a9a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chapter', sa.Column('vedio_duration', sa.String(length=128), nullable=True))
    op.add_column('chapter', sa.Column('vedio_url', sa.String(length=256), nullable=True))
    op.drop_column('chapter', 'video_url')
    op.drop_column('chapter', 'video_duration')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chapter', sa.Column('video_duration', mysql.VARCHAR(length=128), nullable=True))
    op.add_column('chapter', sa.Column('video_url', mysql.VARCHAR(length=256), nullable=True))
    op.drop_column('chapter', 'vedio_url')
    op.drop_column('chapter', 'vedio_duration')
    # ### end Alembic commands ###
