"""empty message

Revision ID: 7875ad37a9a9
Revises: 4fcc2e86f1e0
Create Date: 2018-04-06 21:37:28.365399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7875ad37a9a9'
down_revision = '4fcc2e86f1e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('image_url', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course', 'image_url')
    # ### end Alembic commands ###
